function sanitizeFilename(title, ext) {
  const safe = String(title || 'paper')
    .replace(/[\\/:*?"<>|\r\n\t]/g, '')
    .trim()
    .slice(0, 80)
  return `${safe || 'paper'}.${ext}`
}

function escapeHtml(text) {
  return String(text == null ? '' : text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

const FONT_STACK = '"Malgun Gothic", "맑은 고딕", "Apple SD Gothic Neo", "Noto Sans KR", sans-serif'

const S = {
  title: `font-family:${FONT_STACK}; font-size:18px; font-weight:700; margin:0 0 16px; line-height:1.4; color:#0d3b1f;`,
  section: `font-family:${FONT_STACK}; font-size:14px; font-weight:700; color:#0d3b1f; border-bottom:2px solid #2a8050; padding-bottom:4px; margin:18px 0 10px;`,
  metaTable: `font-family:${FONT_STACK}; width:100%; border-collapse:collapse; font-size:11px; margin-bottom:8px; color:#1a1a1a;`,
  metaTh: 'text-align:left; padding:4px 8px; background:#f0f5f1; color:#0d3b1f; width:90px; border:1px solid #d8e3da; font-weight:600;',
  metaTd: 'padding:4px 8px; border:1px solid #d8e3da;',
  abstract: `font-family:${FONT_STACK}; font-size:11.5px; line-height:1.7; white-space:pre-wrap; padding:10px 12px; background:#fafbfa; border:1px solid #e3e8e4; border-radius:4px; color:#1a1a1a;`,
  reviewWrap: `font-family:${FONT_STACK}; font-size:11.5px; line-height:1.7; color:#1a1a1a;`,
  reviewH2: `font-family:${FONT_STACK}; font-size:13px; font-weight:700; color:#0d3b1f; margin:12px 0 4px;`,
  reviewH3: `font-family:${FONT_STACK}; font-size:12px; font-weight:600; color:#1a4a2a; margin:10px 0 4px;`,
  reviewP: 'margin:4px 0;',
  reviewUl: 'margin:4px 0 4px 20px; padding:0;',
  reviewLi: 'margin:2px 0;',
  footer: `font-family:${FONT_STACK}; margin-top:24px; padding-top:8px; border-top:1px solid #e3e8e4; font-size:9.5px; color:#888; text-align:right;`
}

function reviewToHtml(text) {
  if (!text) return ''
  const lines = text.split('\n')
  let html = ''
  let inList = false
  const closeList = () => { if (inList) { html += '</ul>'; inList = false } }

  for (const line of lines) {
    if (line.startsWith('## ')) {
      closeList()
      html += `<h2 style="${S.reviewH2}">${escapeHtml(line.slice(3))}</h2>`
    } else if (line.startsWith('### ')) {
      closeList()
      html += `<h3 style="${S.reviewH3}">${escapeHtml(line.slice(4))}</h3>`
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      if (!inList) { html += `<ul style="${S.reviewUl}">`; inList = true }
      html += `<li style="${S.reviewLi}">${escapeHtml(line.slice(2))}</li>`
    } else if (line.trim() === '') {
      closeList()
      html += '<div style="height:8px"></div>'
    } else {
      closeList()
      html += `<p style="${S.reviewP}">${escapeHtml(line)}</p>`
    }
  }
  closeList()
  return html
}

function buildExportHtml(paper, reviewText) {
  const authors = (paper.authors && paper.authors.length)
    ? paper.authors.join(', ')
    : '저자 정보 없음'
  const reviewSection = reviewText
    ? `
      <h2 style="${S.section}">AI 분석 결과</h2>
      <div style="${S.reviewWrap}">${reviewToHtml(reviewText)}</div>
    `
    : ''

  return `
    <h1 style="${S.title}">${escapeHtml(paper.title || '제목 없음')}</h1>
    <table style="${S.metaTable}">
      <tr><th style="${S.metaTh}">저자</th><td style="${S.metaTd}">${escapeHtml(authors)}</td></tr>
      <tr><th style="${S.metaTh}">저널</th><td style="${S.metaTd}">${escapeHtml(paper.journal || '-')} · ${escapeHtml(paper.pubDate || '-')}</td></tr>
      <tr><th style="${S.metaTh}">PubMed ID</th><td style="${S.metaTd}">${escapeHtml(paper.pmid || '-')}</td></tr>
      ${paper.pmcid ? `<tr><th style="${S.metaTh}">PMC ID</th><td style="${S.metaTd}">${escapeHtml(paper.pmcid)}</td></tr>` : ''}
    </table>

    <h2 style="${S.section}">Abstract</h2>
    <div style="${S.abstract}">${escapeHtml(paper.abstractText || '초록 정보가 없습니다.')}</div>

    ${reviewSection}

    <div style="${S.footer}">Generated by Bio Agent · ${new Date().toLocaleString('ko-KR')}</div>
  `
}

export async function exportSummaryAsPdf(paper, reviewText) {
  const { default: html2pdf } = await import(/* webpackChunkName: "html2pdf" */ 'html2pdf.js')

  const hider = document.createElement('div')
  hider.style.cssText = 'position:absolute; left:0; top:0; width:0; height:0; overflow:hidden; pointer-events:none;'
  const wrapper = document.createElement('div')
  wrapper.style.cssText = `width:720px; padding:28px; background:#ffffff; color:#1a1a1a; font-family:${FONT_STACK}; box-sizing:border-box;`
  wrapper.innerHTML = buildExportHtml(paper, reviewText)
  hider.appendChild(wrapper)
  document.body.appendChild(hider)

  try {
    await html2pdf()
      .set({
        margin: [12, 12, 14, 12],
        filename: sanitizeFilename(paper.title, 'pdf'),
        image: { type: 'jpeg', quality: 0.95 },
        html2canvas: { scale: 2, useCORS: true, backgroundColor: '#ffffff', windowWidth: 776 },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'] }
      })
      .from(wrapper)
      .save()
  } finally {
    document.body.removeChild(hider)
  }
}

export async function exportSummaryAsWord(paper, reviewText) {
  const docx = await import(/* webpackChunkName: "docx" */ 'docx')
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } = docx

  const paragraphsFromReview = (text) => {
    if (!text) return []
    const out = []
    for (const line of text.split('\n')) {
      if (line.startsWith('## ')) {
        out.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2, spacing: { before: 200, after: 80 } }))
      } else if (line.startsWith('### ')) {
        out.push(new Paragraph({ text: line.slice(4), heading: HeadingLevel.HEADING_3, spacing: { before: 160, after: 60 } }))
      } else if (line.startsWith('- ') || line.startsWith('* ')) {
        out.push(new Paragraph({ text: line.slice(2), bullet: { level: 0 } }))
      } else if (line.trim() === '') {
        out.push(new Paragraph({ text: '' }))
      } else {
        out.push(new Paragraph({ children: [new TextRun(line)] }))
      }
    }
    return out
  }

  const metaParagraph = (label, value) => new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: String(value || '-') })
    ]
  })

  const authors = (paper.authors && paper.authors.length)
    ? paper.authors.join(', ')
    : '저자 정보 없음'

  const children = [
    new Paragraph({
      text: paper.title || '제목 없음',
      heading: HeadingLevel.HEADING_1,
      spacing: { after: 200 }
    }),
    metaParagraph('저자', authors),
    metaParagraph('저널', `${paper.journal || '-'} · ${paper.pubDate || '-'}`),
    metaParagraph('PubMed ID', paper.pmid),
  ]
  if (paper.pmcid) children.push(metaParagraph('PMC ID', paper.pmcid))

  children.push(new Paragraph({ text: '' }))
  children.push(new Paragraph({
    text: 'Abstract',
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 100 }
  }))
  for (const line of String(paper.abstractText || '초록 정보가 없습니다.').split('\n')) {
    children.push(new Paragraph({ children: [new TextRun(line)] }))
  }

  if (reviewText) {
    children.push(new Paragraph({ text: '' }))
    children.push(new Paragraph({
      text: 'AI 분석 결과',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 240, after: 100 }
    }))
    children.push(...paragraphsFromReview(reviewText))
  }

  children.push(new Paragraph({ text: '' }))
  children.push(new Paragraph({
    children: [new TextRun({
      text: `Generated by Bio Agent · ${new Date().toLocaleString('ko-KR')}`,
      italics: true,
      color: '888888',
      size: 18
    })],
    alignment: AlignmentType.RIGHT
  }))

  const doc = new Document({ sections: [{ children }] })
  const blob = await Packer.toBlob(doc)
  triggerBlobDownload(blob, sanitizeFilename(paper.title, 'docx'))
}

function triggerBlobDownload(blob, filename) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  setTimeout(() => URL.revokeObjectURL(url), 200)
}

export function pmcPdfUrl(pmcid) {
  if (!pmcid) return null
  return `https://www.ncbi.nlm.nih.gov/pmc/articles/${pmcid}/pdf/`
}
